# manakin accounting plan
# [
#   (
#       manakin account class,
#       use for annotation,
#       have sequence,
#       [
#           (prefix account for translate tiime, sequence begin index),
#           ...
#       ],
#      account label,
#      sequence label,
#   )
# ]

manakin_accounting_plan = [
    (
        '101100',
        False,
        False,
        [
            ('1011', None),
        ],
        'Capital souscrit - non appelé',
        None,
    ),
    (
        '101200',
        False,
        False,
        [
            ('1012', None),
        ],
        'Capital souscrit - appelé, non versé',
        None,
    ),
    (
        '101300',
        True,
        False,
        [
            ('1013', None),
        ],
        'Capital appelé versé',
        None,
    ),
    (
        '104100',
        False,
        False,
        [
            ('1041', None),
        ],
        'Primes d''émission',
        None,
    ),
    (
        '106100',
        False,
        False,
        [
            ('1061', None),
        ],
        'Réserve légale',
        None,
    ),
    (
        '106300',
        False,
        False,
        [
            ('1063', None),
        ],
        'Réserves statutaires ou contractuelles',
        None,
    ),
    (
        '106400',
        False,
        False,
        [
            ('1064', None),
        ],
        'Réserves réglementées',
        None,
    ),
    (
        '106800',
        False,
        False,
        [
            ('1068', None),
        ],
        'Autres réserves',
        None,
    ),
    (
        '108000',
        True,
        False,
        [
            ('108', None),
        ],
        'Compte de l''exploitant',
        None,
    ),
    (
        '109000',
        False,
        False,
        [
            ('109', None),
        ],
        'Actionnaires : capital souscrit - non appelé',
        None,
    ),
    (
        '110000',
        False,
        False,
        [
            ('110', None),
        ],
        'Report à nouveau (solde créditeur)',
        None,
    ),
    (
        '119000',
        False,
        False,
        [
            ('119', None),
        ],
        'Report à nouveau (solde débiteur)',
        None,
    ),
    (
        '120000',
        False,
        False,
        [
            ('120', None),
        ],
        'Résultat de l''exercice (bénéfice)',
        None,
    ),
    (
        '129000',
        False,
        False,
        [
            ('129', None),
        ],
        'Résultat de l''exercice (perte)',
        None,
    ),
    (
        '131000',
        True,
        False,
        [
            ('131', None),
        ],
        'Subventions d''équipement',
        None,
    ),
    (
        '139000',
        False,
        False,
        [
            ('139', None),
        ],
        'Subventions d''investissement inscrites au compte de résultat',
        None,
    ),
    (
        '142400',
        False,
        False,
        [
            ('1424', None),
        ],
        'Provisions pour investissement (participation des salariés)',
        None,
    ),
    (
        '143000',
        False,
        False,
        [
            ('143', None),
        ],
        'Provisions réglementées relatives aux stocks',
        None,
    ),
    (
        '145000',
        False,
        False,
        [
            ('145', None),
        ],
        'Amortissements dérogatoires',
        None,
    ),
    (
        '151000',
        False,
        False,
        [
            ('1510', None),
        ],
        'Provisions pour risques',
        None,
    ),
    (
        '151100',
        False,
        False,
        [
            ('1511', None),
        ],
        'Provisions pour litiges',
        None,
    ),
    (
        '151400',
        False,
        False,
        [
            ('1514', None),
        ],
        'Provisions pour amendes et pénalités',
        None,
    ),
    (
        '151500',
        False,
        False,
        [
            ('1515', None),
        ],
        'Provisions pour pertes de change',
        None,
    ),
    (
        '158000',
        False,
        False,
        [
            ('158', None),
        ],
        'Autres provisions pour charges',
        None,
    ),
    (
        '164000',
        True,
        True,
        [
            ('164', 3),
        ],
        'Emprunt',
        'numéro d''emprunt',
    ),
    (
        '165000',
        True,
        True,
        [
            ('1650', 4),
        ],
        'Caution reçue',
        'numéro de caution',
    ),
    (
        '165100',
        True,
        False,
        [
            ('1651', None),
        ],
        'Dépôts',
        None,
    ),
    (
        '165500',
        True,
        False,
        [
            ('1655', None),
        ],
        'Cautionnements',
        None,
    ),
    (
        '166000',
        True,
        False,
        [
            ('166', None),
        ],
        'Participation des salariés aux résultats',
        None,
    ),
    (
        '167400',
        True,
        False,
        [
            ('1674', None),
        ],
        'Participation des salariés aux résultats',
        None,
    ),
    (
        '168000',
        True,
        False,
        [
            ('1680', None),
            ('1681', None),
            ('1682', None),
            ('1683', None),
            ('1684', None),
            ('1685', None),
            ('1686', None),
            ('1687', None),
        ],
        'Autres emprunts et dettes assimilées',
        None,
    ),
    (
        '168800',
        True,
        False,
        [
            ('1688', None),
        ],
        'Intérêts courus',
        None,
    ),
    (
        '201000',
        True,
        False,
        [
            ('201', None),
        ],
        'Frais d''établissement',
        None,
    ),
    (
        '203000',
        True,
        False,
        [
            ('203', None),
        ],
        'Frais de recherche et de développement',
        None,
    ),
    (
        '205000',
        True,
        False,
        [
            ('20500', None),
            ('2054', None),
            ('2057', None),
        ],
        'Concessions et droits similaires, brevets, licences, marques, procédés, logiciels, droits'
        'et valeurs similaires',
        None,
    ),
    (
        '205100',
        True,
        False,
        [
            ('20510', None),
        ],
        'Droit d''entrée franchise',
        None,
    ),
    (
        '205110',
        True,
        False,
        [
            ('20511', None),
        ],
        'Site Internet',
        None,
    ),
    (
        '205120',
        True,
        False,
        [
            ('20512', None),
        ],
        'Logiciel',
        None,
    ),
    (
        '206000',
        True,
        False,
        [
            ('206', None),
        ],
        'Droit au bail',
        None,
    ),
    (
        '207000',
        True,
        False,
        [
            ('207', None),
        ],
        'Fond commercial',
        None,
    ),
    (
        '208000',
        True,
        False,
        [
            ('208', None),
        ],
        'Autres immobilisations incorporelles',
        None,
    ),
    (
        '211000',
        True,
        False,
        [
            ('211', None),
        ],
        'Terrains ',
        None,
    ),
    (
        '212000',
        True,
        False,
        [
            ('212', None),
        ],
        'Agencements et aménagements de terrains (même ventilation que celle du compte 211)',
        None,
    ),
    (
        '213000',
        True,
        False,
        [
            ('2130', None),
        ],
        'Constructions',
        None,
    ),
    (
        '213100',
        True,
        False,
        [
            ('2131', None),
        ],
        'Immeuble, constructions',
        None,
    ),
    (
        '214000',
        True,
        False,
        [
            ('214', None),
        ],
        'Constructions sur sol d''autrui (même ventilation que celle du compte 213)',
        None,
    ),
    (
        '215000',
        True,
        False,
        [
            ('2150', None),
        ],
        'Installations techniques, matériels et outillage industriels',
        None,
    ),
    (
        '215100',
        True,
        False,
        [
            ('2151', None),
        ],
        'Matériel et outillage de travail',
        None,
    ),
    (
        '215400',
        True,
        False,
        [
            ('2154', None),
        ],
        'Matériel et outillage de travail',
        None,
    ),
    (
        '218000',
        True,
        False,
        [
            ('2180', None),
        ],
        'Autres immobilisations corporelles',
        None,
    ),
    (
        '218100',
        True,
        False,
        [
            ('2181', None),
        ],
        'Aménagement et agencement de locaux',
        None,
    ),
    (
        '218200',
        True,
        False,
        [
            ('2182', None),
        ],
        'Véhicule',
        None,
    ),
    (
        '218300',
        True,
        False,
        [
            ('2183', None),
        ],
        'Matériel Informatique',
        None,
    ),
    (
        '218400',
        True,
        False,
        [
            ('2184', None),
        ],
        'Mobilier',
        None,
    ),
    (
        '218500',
        True,
        False,
        [
            ('2185', None),
        ],
        'Cheptel',
        None,
    ),
    (
        '231000',
        False,
        False,
        [
            ('231', None),
        ],
        'Immobilisations corporelles en cours',
        None,
    ),
    (
        '261000',
        True,
        False,
        [
            ('2610', None),
        ],
        'Titres de participation',
        None,
    ),
    (
        '261100',
        True,
        False,
        [
            ('2611', None),
        ],
        'Actions',
        None,
    ),
    (
        '261800',
        True,
        False,
        [
            ('2618', None),
        ],
        'Autres titres',
        None,
    ),
    (
        '266000',
        True,
        False,
        [
            ('266', None),
        ],
        'Autres formes de participation',
        None,
    ),
    (
        '267000',
        True,
        False,
        [
            ('267', None),
        ],
        'Créances rattachées à des participations',
        None,
    ),
    (
        '268000',
        True,
        False,
        [
            ('268', None),
        ],
        'Créances rattachées à des sociétés en participation',
        None,
    ),
    (
        '271000',
        True,
        False,
        [
            ('271', None),
        ],
        'Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille (droit de propriété)',
        None
    ),
    (
        '272000',
        True,
        False,
        [
            ('272', None),
        ],
        'Titres immobilisés (droit de créance)',
        None,
    ),
    (
        '273000',
        True,
        False,
        [
            ('273', None),
        ],
        'Titres immobilisés de l''activité de portefeuille',
        None,
    ),
    (
        '274000',
        True,
        False,
        [
            ('274', None),
        ],
        'Prêts',
        None,
    ),
    (
        '275000',
        True,
        False,
        [
            ('275', None),
        ],
        'Dépôt cautions versées',
        None,
    ),
    (
        '280100',
        False,
        False,
        [
            ('2801', None),
        ],
        'Amortissement Frais d''établissement',
        None,
    ),
    (
        '280300',
        False,
        False,
        [
            ('2803', None),
        ],
        'Amortissement Frais de recherche et de développement',
        None,
    ),
    (
        '280500',
        False,
        False,
        [
            ('2805', None),
        ],
        'Amortissement Concessions et droits similaires, brevets, licences, logiciels, droits et valeurs similaires',
        None,
    ),
    (
        '280700',
        False,
        False,
        [
            ('28070000', None)
        ],
        'Amortissement Fonds commercial',
        None,
    ),
    (
        '280800',
        False,
        False,
        [
            ('2808', None),
        ],
        'Amortissement Autres immobilisations incorporelles',
        None,
    ),
    (
        '281100',
        False,
        False,
        [
            ('2811', None),
        ],
        'Amortissement Terrains de gisement',
        None,
    ),
    (
        '281200',
        False,
        False,
        [
            ('2812', None),
        ],
        'Amortissement Agencements, aménagements de terrains (même ventilation que celle du compte 212)',
        None,
    ),
    (
        '281300',
        False,
        False,
        [
            ('2813', None),
        ],
        'Amortissement Constructions (même ventilation que celle du compte 213)',
        None,
    ),
    (
        '281310',
        False,
        False,
        [
            ('28131', None),
        ],
        'Amortissement Immeuble, constructions',
        None,
    ),
    (
        '281400',
        False,
        False,
        [
            ('2814', None),
        ],
        'Amortissement Constructions sur sol d''autrui (même ventilation que celle du compte 214)',
        None,
    ),
    (
        '281500',
        False,
        False,
        [
            ('2815', None),
        ],
        'Amortissement Installations, matériel et outillage industriels (même ventilation que celle du compte 215)',
        None,
    ),
    (
        '281540',
        False,
        False,
        [
            ('28154', None),
        ],
        'Amortissement Matériel et outillage de travail',
        None,
    ),
    (
        '281800',
        False,
        False,
        [
            ('28180', None),
        ],
        'Amortissement Autres immobilisations corporelles (même ventilation que celle du compte 218)',
        None,
    ),
    (
        '281810',
        False,
        False,
        [
            ('28181', None),
        ],
        'Amortissement Aménagement et agencement de locaux',
        None,
    ),
    (
        '281820',
        False,
        False,
        [
            ('28182', None),
        ],
        'Amortissement Véhicule',
        None,
    ),
    (
        '281830',
        False,
        False,
        [
            ('28183', None),
        ],
        'Amortissement Matériel Informatique',
        None,
    ),
    (
        '281840',
        False,
        False,
        [
            ('28184', None),
        ],
        'Amortissement Mobilier',
        None,
    ),
    (
        '281850',
        False,
        False,
        [
            ('28185', None),
        ],
        'Amortissement Cheptel',
        None,
    ),
    (
        '285100',
        False,
        False,
        [
            ('28510', None),
        ],
        'Amortissement Droit d''entrée franchise',
        None,
    ),
    (
        '285110',
        False,
        False,
        [
            ('28511', None),
        ],
        'Amortissement Site Internet',
        None,
    ),
    (
        '285120',
        False,
        False,
        [
            ('28512', None),
        ],
        'Amortissement Logiciel',
        None,
    ),
    (
        '286000',
        False,
        False,
        [
            ('286', None),
        ],
        'Amortissement Droit au bail',
        None,
    ),
    (
        '290500',
        False,
        False,
        [
            ('2905', None),
        ],
        'Dépréciation Marques, procédés, droits et valeurs similaires',
        None,
    ),
    (
        '290600',
        False,
        False,
        [
            ('2906', None),
        ],
        'Dépréciation Droit au bail',
        None,
    ),
    (
        '290700',
        False,
        False,
        [
            ('2907', None),
        ],
        'Dépréciation Fonds commercial',
        None,
    ),
    (
        '290800',
        False,
        False,
        [
            ('2908', None),
        ],
        'Dépréciation Autres immobilisations incorporelles',
        None,
    ),
    (
        '291000',
        False,
        False,
        [
            ('2910', None),
        ],
        'Dépréciation Dépréciations des immobilisations corporelles',
        None,
    ),
    (
        '291100',
        False,
        False,
        [
            ('2911', None),
        ],
        'Dépréciation Terrains (autres que terrains de gisement)',
        None,
    ),
    (
        '292000',
        False,
        False,
        [
            ('292', None),
        ],
        'Dépréciations des immobilisations mises en concession',
        None,
    ),
    (
        '293000',
        False,
        False,
        [
            ('2930', None),
        ],
        'Dépréciations des immobilisations en cours',
        None,
    ),
    (
        '293100',
        False,
        False,
        [
            ('2931', None),
        ],
        'Dépréciations Immobilisations corporelles en cours',
        None,
    ),
    (
        '293200',
        False,
        False,
        [
            ('2932', None),
        ],
        'Dépréciations Immobilisations incorporelles en cours',
        None,
    ),
    (
        '296000',
        False,
        False,
        [
            ('2960', None),
        ],
        'Provisions pour dépréciation des participations et créances rattachées à des participations',
        None,
    ),
    (
        '296100',
        False,
        False,
        [
            ('2961', None),
        ],
        'Dépréciations Titres de participation',
        None,
    ),
    (
        '296600',
        False,
        False,
        [
            ('2966', None),
        ],
        'Dépréciations Autres formes de participation',
        None,
    ),
    (
        '296700',
        False,
        False,
        [
            ('2967', None),
        ],
        'Dépréciations Créances rattachées à des participations',
        None,
    ),
    (
        '296800',
        False,
        False,
        [
            ('2968', None),
        ],
        'Dépréciations Créances rattachées à des sociétés en participation',
        None,
    ),
    (
        '297000',
        False,
        False,
        [
            ('2970', None),
        ],
        'Provisions pour dépréciation des autres immobilisations financières',
        None,
    ),
    (
        '297100',
        False,
        False,
        [
            ('2971', None),
        ],
        'Dépréciations Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille - droit de'
        ' propriété',
        None,
    ),
    (
        '297200',
        False,
        False,
        [
            ('2972', None),
        ],
        'Dépréciations Titres immobilisés - droit de créance',
        None,
    ),
    (
        '297300',
        False,
        False,
        [
            ('2973', None),
        ],
        'Dépréciations Titres immobilisés de l''activité de portefeuille',
        None,
    ),
    (
        '297400',
        False,
        False,
        [
            ('2974', None),
        ],
        'Dépréciations Prêts',
        None,
    ),
    (
        '297500',
        False,
        False,
        [
            ('2975', None),
        ],
        'Dépréciations Dépôts et cautionnements versés ',
        None,
    ),
    (
        '297600',
        False,
        False,
        [
            ('2976', None),
        ],
        'Dépréciations Autres créances immobilisées',
        None,
    ),
    (
        '321000',
        False,
        False,
        [
            ('321', None),
        ],
        'Matières consommables',
        None,
    ),
    (
        '326000',
        False,
        False,
        [
            ('326', None),
        ],
        'Emballages',
        None,
    ),
    (
        '331000',
        False,
        False,
        [
            ('331', None),
        ],
        'Produits en cours',
        None,
    ),
    (
        '335000',
        False,
        False,
        [
            ('335', None),
        ],
        'Travaux en cours',
        None,
    ),
    (
        '341000',
        False,
        False,
        [
            ('341', None),
        ],
        'Etudes en cours',
        None,
    ),
    (
        '345000',
        False,
        False,
        [
            ('345', None),
        ],
        'Prestations de services en cours',
        None,
    ),
    (
        '351000',
        False,
        False,
        [
            ('351', None),
        ],
        'Produits intermédiaires',
        None,
    ),
    (
        '355000',
        False,
        False,
        [
            ('355', None),
        ],
        'Produits finis',
        None,
    ),
    (
        '391000',
        False,
        False,
        [
            ('391', None),
        ],
        'Provisions pour dépréciation des matières premières (et fournitures)',
        None,
    ),
    (
        '395000',
        False,
        False,
        [
            ('395', None),
        ],
        'Provisions pour dépréciation des stocks de produits',
        None,
    ),
    (
        '401000',
        False,
        True,
        [
            ('401', 3),
        ],
        'Fournisseurs', 'numéro de fournisseur',
    ),
    (
        '404000',
        False,
        True,
        [
            ('404', 3)
        ],
        'Fournisseurs d''immobilisations', 'numéro de fournisseur',
    ),
    (
        '408000',
        False,
        True,
        [
            ('4080', 4),
        ],
        'Fournisseurs - Factures non parvenues',
        'numéro de fournisseur',
    ),
    (
        '408100',
        False,
        True,
        [
            ('4081', 4),
        ],
        'Fournisseurs-Factures à établir',
        'numéro de fournisseur',
    ),
    (
        '409000',
        False,
        True,
        [
            ('4090', 4),
        ],
        'Fournisseurs débiteurs',
        'numéro de fournisseur',
    ),
    (
        '409800',
        False,
        True,
        [
            ('4098', 4),
        ],
        'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus',
        'numéro de fournisseur',
    ),
    (
        '411000',
        False,
        True,
        [
            ('411', 3),
        ],
        'Clients',
        'numéro de client',
    ),
    (
        '413000',
        False,
        True,
        [
            ('413', 3),
        ],
        'Clients - Effets à recevoir',
        'numéro de client',
    ),
    (
        '416000',
        False,
        True,
        [
            ('416', 3),
        ],
        'Clients douteux ou litigieux',
        'numéro de client',
    ),
    (
        '418000',
        False,
        True,
        [
            ('4180', 4),
        ],
        'Clients - Produits non encore facturés',
        'numéro de client',
    ),
    (
        '418100',
        False,
        True,
        [
            ('4181', 4),
        ],
        'Clients - Factures à établir',
        'numéro de client',
    ),
    (
        '419000',
        False,
        True,
        [
            ('4190', 4),
        ],
        'Clients créditeurs',
        'numéro de client',
    ),
    (
        '419800',
        False,
        True,
        [
            ('4198', 4),
        ],
        'Rabais, remises, ristournes à accorder et autres avoirs à établir',
        'numéro de client',
    ),
    (
        '421000',
        True,
        True,
        [
            ('421', 3),
        ],
        'Personnel - Rémunérations dues',
        'numéro de salarié',
    ),
    (
        '425000',
        True,
        True,
        [
            ('425', 3),
        ],
        'Personnel - Avances et acomptes',
        'numéro de salarié',
    ),
    (
        '428600',
        True,
        True,
        [
            ('4286', 4),
        ],
        'Autres charges à payer',
        'numéro de salarié',
    ),
    (
        '428700',
        True,
        True,
        [
            ('4287', 4),
        ],
        'Produits à recevoir',
        'numéro de salarié',
    ),
    (
        '431000',
        True,
        True,
        [
            ('431', 3),
        ],
        'Sécurité sociale',
        'numéro organisme social',
    ),
    (
        '437000',
        True,
        True,
        [
            ('437', 3),
        ],
        'Autres organismes sociaux',
        'numéro organisme social',
    ),
    (
        '438000',
        True,
        True,
        [
            ('4380', 4),
            ('4381', 3),
            ('4383', 3),
            ('4384', 3),
            ('4385', 3),
            ('4388', 3),
            ('4389', 3),
        ],
        'Organismes sociaux - Charges à payer et produits à recevoir',
        'numéro organisme social',
    ),
    (
        '438200',
        False,
        True,
        [
            ('4382', 4),
        ],
        'Charges sociales sur congés à payer',
        'numéro organisme social',
    ),
    (
        '438600',
        True,
        True,
        [
            ('4386', 4),
        ],
        'Autres charges à payer',
        'numéro organisme social',
    ),
    (
        '438700',
        False,
        True,
        [
            ('4387', 4),
        ],
        'Produits à recevoir',
        'numéro organisme social',
    ),
    (
        '441000',
        False,
        False,
        [
            ('441', None),
        ],
        'État - Subventions à recevoir',
        None,
    ),
    (
        '444000',
        True,
        False,
        [
            ('444', None),
            ('649', None),
            ('695', None),
        ],
        'IS',
        None),
    (
        '445200',
        False,
        False,
        [
            ('4452', None),
        ],
        'TVA déductible intra',
        None,
    ),
    (
        '445510',
        True,
        False, [
            ('44550', None),
            ('44551', None),
        ],
        'TVA à payer',
        None,
    ),
    (
        '445620',
        False,
        False,
        [
            ('445620', None),
        ],
        'TVA déductible sur immobilisation',
        None,
    ),
    (
        '445661',
        True,
        False,
        [
            ('445660', None),
            ('445661', None),
            ('445663', None),
        ],
        'TVA déductible sur ABS',
        None,
    ),
    (
        '445670',
        True,
        False,
        [
            ('44567', None),
        ],
        'Crédit de TVA',
        None,
    ),
    (
        '445710',
        False,
        False,
        [
            ('44571021', None),
        ],
        'TVA collectée 2,1%',
        None,
    ),
    (
        '445710',
        False,
        False,
        [
            ('44571055', None),
        ],
        'TVA collectée 5,5%',
        None,
    ),
    (
        '445710',
        False,
        False,
        [
            ('44571070', None),
        ],
        'TVA collectée 7%',
        None,
    ),
    (
        '445710',
        False,
        False,
        [
            ('44571085', None),
        ],
        'TVA collectée 8,5%',
        None,
    ),
    (
        '445711',
        False,
        False,
        [
            ('44571100', None),
        ],
        'TVA collectée 10%',
        None,
    ),
    (
        '445711',
        False,
        False,
        [
            ('44571196', None),
        ],
        'TVA collectée 19,6%',
        None,
    ),
    (
        '445712',
        False,
        False,
        [
            ('44571200', None),
        ],
        'TVA collectée 20%',
        None,
    ),
    (
        '445800',
        True,
        False,
        [
            ('44580', None),
            ('44581', None),
            ('44582', None),
            ('44583', None),
        ],
        'Acomptes TVA',
        None,
    ),
    (
        '445860',
        False,
        False,
        [
            ('44586', None),
        ],
        'Taxes sur le chiffre d''affaires sur factures non parvenues',
        None,
    ),
    (
        '445870',
        False,
        False,
        [
            ('44587', None),
        ],
        'Taxes sur le chiffre d''affaires sur factures à établir',
        None,
    ),
    (
        '448600',
        False,
        False,
        [
            ('4486', None),
        ],
        'Charges à payer',
        None,
    ),
    (
        '448700',
        False,
        False,
        [
            ('4487', None),
        ],
        'Produits à recevoir',
        None,
    ),
    (
        '451000',
        True,
        True,
        [
            ('451', 3),
        ],
        'Groupe',
        'Associés',
    ),
    (
        '455000',
        True,
        True,
        [
            ('4550', 3),
            ('4551', 3),
            ('4552', 3),
            ('4553', 3),
            ('4554', 3),
            ('4555', 3),
            ('4556', 3),
            ('4557', 3),
        ],
        'Apport et prélèvement dirigeant',
        'numéro d''associés',
    ),
    (
        '455800',
        False,
        True,
        [
            ('45580000', 4),
        ],
        'Intérêts courus',
        'numéro d''associés',
    ),
    (
        '457000',
        True,
        False,
        [
            ('457', None),
        ],
        'Associés - Dividendes à payer',
        None,
    ),
    (
        '458800',
        False,
        False,
        [
            ('4588', None),
        ],
        'Intérêts courus',
        None,
    ),
    (
        '467000',
        True,
        False,
        [
            ('460', None),
            ('467', None),
        ],
        'Débiteurs et créditeurs divers',
        None,
    ),
    (
        '468600',
        False,
        False,
        [
            ('4686', None),
        ],
        'Divers - Charges à payer',
        None,
    ),
    (
        '468700',
        False,
        False,
        [
            ('4687', None),
        ],
        'Divers - Produits à recevoir',
        None,
    ),
    (
        '472000',
        False,
        False,
        [
            ('472', None),
        ],
        'Comptes d''attente',
        None,
    ),
    (
        '476000',
        False,
        False,
        [
            ('476', None),
        ],
        'Différence de conversion - Actif',
        None,
    ),
    (
        '477000',
        False,
        False,
        [
            ('477', None),
        ],
        'Différences de conversion - Passif',
        None,
    ),
    (
        '486000',
        False,
        False,
        [
            ('486', None),
        ],
        'Charges constatées d''avance',
        None,
    ),
    (
        '487000',
        False,
        False,
        [
            ('487', None),
        ],
        'Produits constatés d''avance',
        None,
    ),
    (
        '491000',
        False,
        False,
        [
            ('491', None),
        ],
        'Provisions pour dépréciation des comptes de clients',
        None,
    ),
    (
        '503000',
        False,
        False,
        [
            ('503', None),
        ],
        'Valeurs mobilières de placement',
        None,
    ),
    (
        '508000',
        False,
        True,
        [
            ('508', 3),
        ],
        'Compte à terme', 'numéro de CAT',
    ),
    (
        '511000',
        False,
        False,
        [],
        'Valeurs à l''encaissement',
        None,
    ),
    (
        '512000',
        False,
        True,
        [],
        'Banques',
        'numéro de banque',
    ),
    (
        '514000',
        False,
        True,
        [],
        'Chèques postaux',
        'numéro de banque',
    ),
    (
        '530000',
        False,
        True,
        [],
        'Caisse',
        'numéro de caisse',
    ),
    (
        '580000',
        True,
        False,
        [
            ('58', None),
            ('511', None),
            ('512', None),
            ('53', None),
        ],
        'Virement inter banques',
        None,
    ),
    (
        '590000',
        False,
        False,
        [
            ('59', None),
        ],
        'Provisions pour dépréciation des valeurs mobilières de placement',
        None,
    ),
    (
        '601000',
        True,
        False,
        [
            ('601', None),
        ],
        'Achats matières',
        None,
    ),
    (
        '602000',
        True,
        False,
        [
            ('6020', None),
        ],
        'Achats stockés - Autres approvisionnements',
        None,
    ),
    (
        '602100',
        True,
        False,
        [
            ('6021', None),
        ],
        'Achats stockés matières consommables',
        None,
    ),
    (
        '602200',
        True,
        False,
        [
            ('6022', None),
        ],
        'Achats stockés fournitures consommables',
        None,
    ),
    (
        '602600',
        True,
        False,
        [
            ('6026', None),
        ],
        'Emballages',
        None,
    ),
    (
        '603210',
        False,
        False,
        [
            ('60321', None),
        ],
        'Variation de stock Matières consommables',
        None,
    ),
    (
        '603260',
        False,
        False,
        [
            ('60326', None),
        ],
        'Variation de stock Emballages',
        None,
    ),
    (
        '603310',
        False,
        False,
        [
            ('60331', None),
        ],
        'Variation de stock Produits en cours',
        None,
    ),
    (
        '603350',
        False,
        False,
        [
            ('60335', None),
        ],
        'Variation de stock Travaux en cours',
        None,
    ),
    (
        '603410',
        False,
        False,
        [
            ('60341', None),
        ],
        'Variation de stock Etudes en cours',
        None,
    ),
    (
        '603450',
        False,
        False,
        [
            ('60345', None),
        ],
        'Variation de stock Prestations de services en cours',
        None,
    ),
    (
        '603510',
        False,
        False,
        [
            ('60351', None),
        ],
        'Variation de stock Produits intermédiaires',
        None,
    ),
    (
        '603550',
        False,
        False,
        [
            ('60355', None),
        ],
        'Variation de stock Produits finis',
        None,
    ),
    (
        '604000',
        True,
        False,
        [
            ('604', None),
        ],
        'Prestataires de services',
        None,
    ),
    (
        '605000',
        True,
        False,
        [
            ('605', None),
        ],
        ' Achats de matériel, équipements et travaux',
        None,
    ),
    (
        '606100',
        True,
        False,
        [
            ('60610', None),
        ],
        'Electricité',
        None,
    ),
    (
        '606110',
        True,
        False,
        [
            ('60611', None),
        ],
        'Eau',
        None,
    ),
    (
        '606120',
        True,
        False,
        [
            ('60612', None),
        ],
        'Gaz',
        None,
    ),
    (
        '606130',
        True,
        False,
        [
            ('60613', None),
            ('6062', None),
            ('6065', None),
            ('6066', None),
            ('6067', None),
            ('6068', None),
            ('6069', None),
        ],
        'Achats fournitures, petits équipements non stockés',
        None,
    ),
    (
        '606140',
        True,
        False,
        [
            ('60614', None),
        ],
        'Achats fournitures de bureau non stockées',
        None,
    ),
    (
        '606150',
        True,
        False,
        [
            ('60615', None),
        ],
        'Essence',
        None,
    ),
    (
        '606160',
        True,
        False,
        [
            ('60616', None),
        ],
        'Gas-Oil',
        None,
    ),
    (
        '606300',
        True,
        False,
        [
            ('6063', None),
        ],
        'Accessoires et petits matériels',
        None,
    ),
    (
        '606400',
        True,
        False,
        [
            ('6064', None),
        ],
        'Fournitures de bureau',
        None,
    ),
    (
        '607000',
        True,
        False,
        [
            ('607', None),
        ],
        'Achats marchandises',
        None,
    ),
    (
        '608000',
        True,
        False,
        [
            ('608', None),
        ],
        'Frais accessoires incorporés aux achats',
        None,
    ),
    (
        '609000',
        True,
        False,
        [
            ('609', None),
        ],
        'Rabais, remises et ristournes obtenus sur achats',
        None,
    ),
    (
        '611000',
        True,
        False,
        [
            ('611', None),
        ],
        'Sous-traitance',
        None,
    ),
    (
        '612000',
        True,
        False,
        [
            ('6120', None),
            ('6122', None),
            ('6123', None),
            ('6124', None),
            ('6125', None),
            ('6129', None),
        ],
        'Crédit bail matériel',
        None,),
    (
        '612100',
        True,
        False,
        [
            ('6121', None),
        ],
        'Crédit bail véhicule',
        None,
    ),
    (
        '613200',
        True,
        False,
        [
            ('6132', None),
        ],
        'Locations immobilières',
        None,
    ),
    (
        '613500',
        True,
        False,
        [
            ('61350', None),
            ('6130', None),
            ('6131', None),
            ('6133', None),
            ('6134', None),
        ],
        'Location de matériel',
        None,
    ),
    (
        '613510',
        True,
        False,
        [
            ('61351', None),
            ('61352', None),
            ('61353', None),
            ('61354', None),
            ('61355', None),
            ('61356', None),
            ('61357', None),
            ('61358', None),
            ('61359', None),
        ],
        'Location véhicule',
        None,
    ),
    (
        '614000',
        True,
        False,
        [
            ('614', None),
        ],
        'Charges locatives',
        None,
    ),
    (
        '615000',
        True,
        False,
        [
            ('6150', None),
        ],
        'Nettoyage, entretien et réparations',
        None,
    ),
    (
        '615100',
        True,
        False,
        [
            ('6151', None),
        ],
        'Entretien véhicule',
        None,
    ),
    (
        '615200',
        True,
        False,
        [
            ('6152', None),
        ],
        'Entretiens et réparations sur biens immobiliers',
        None,
    ),
    (
        '615500',
        True,
        False,
        [
            ('6155', None),
        ],
        'Entretiens et réparations sur biens mobiliers',
        None,
    ),
    (
        '615600',
        True,
        False,
        [
            ('6156', None),
        ],
        'Maintenance',
        None,
    ),
    (
        '616000',
        True,
        False,
        [
            ('616', None),
        ],
        'Assurances',
        None,
    ),
    (
        '617000',
        True,
        False,
        [
            ('617', None),
        ],
        'Etudes et recherches',
        None,
    ),
    (
        '618100',
        True,
        False,
        [
            ('6181', None),
            ('6180', None),
            ('6182', None),
            ('6183', None),
            ('6184', None),
            ('6186', None),
            ('6187', None),
            ('6188', None),
            ('6189', None),
        ],
        'Documentation',
        None,
    ),
    (
        '618500',
        True,
        False,
        [
            ('6185', None),
        ],
        'Frais de colloques, séminaires, conférences',
        None,
    ),
    (
        '621000',
        True,
        False,
        [
            ('621', None),
        ],
        'Personnel extérieur à l''entreprise',
        None,
    ),
    (
        '622000',
        True,
        False,
        [
            ('6220', None),
        ],
        'Rémunérations d''intermédiaires et honoraires',
        None,
    ),
    (
        '622100',
        True,
        False,
        [
            ('6221', None),
        ],
        'Commissions et courtages sur achats',
        None,
    ),
    (
        '622200',
        True,
        False,
        [
            ('6222', None),
        ],
        'Commissions et courtages sur ventes',
        None,
    ),
    (
        '622500',
        False,
        False,
        [
            ('6225', None),
        ],
        'Rémunération d''affacturage',
        None,
    ),
    (
        '622600',
        True,
        False,
        [
            ('6226', None),
        ],
        'Honoraires',
        None,
    ),
    (
        '622700',
        True,
        False,
        [
            ('6227', None),
        ],
        'Frais administratifs',
        None,
    ),
    (
        '622800',
        True,
        False,
        [
            ('6228', None),
        ],
        'Rémunérations d''intérmédiaires et honoraires divers',
        None,
    ),
    (
        '623000',
        True,
        False,
        [
            ('6230', None),
        ],
        'Publicité, publications, relations publiques',
        None,
    ),
    (
        '623100',
        True,
        False,
        [
            ('6231', None),
        ],
        'Publicité',
        None,
    ),
    (
        '623200',
        True,
        False,
        [
            ('6232', None),
        ],
        'Echantillons',
        None,
    ),
    (
        '623300',
        True,
        False,
        [
            ('6233', None),
        ],
        'Foires et expositions',
        None,
    ),
    (
        '623400',
        True,
        False,
        [
            ('6234', None),
        ],
        'Cadeau client',
        None,
    ),
    (
        '623600',
        True,
        False,
        [
            ('6236', None),
        ],
        'Catalogues et imprimés',
        None,
    ),
    (
        '623700',
        True,
        False,
        [
            ('6237', None),
        ],
        'Publications',
        None,
    ),
    (
        '623800',
        True,
        False,
        [
            ('6238', None),
        ],
        'Divers (pourboires, dont courant)',
        None,
    ),
    (
        '624100',
        True,
        False,
        [
            ('6241', None),
        ],
        'Transports sur achats',
        None,
    ),
    (
        '624200',
        True,
        False,
        [
            ('6242', None),
        ],
        'Transports sur ventes',
        None,
    ),
    (
        '624400',
        True,
        False,
        [
            ('6244', None),
        ],
        'Transports administratifs',
        None,
    ),
    (
        '624800',
        False,
        False,
        [
            ('6248', None),
        ],
        'Transports divers',
        None,
    ),
    (
        '625100',
        True,
        False,
        [
            ('6251', None),
            ('6250', None),
        ],
        'Frais de transport',
        None,
    ),
    (
        '625200',
        True,
        False,
        [
            ('6252', None),
        ],
        'Hôtels',
        None,
    ),
    (
        '625300',
        True,
        False,
        [
            ('6253', None),
        ],
        'Restaurants',
        None,
    ),
    (
        '625400',
        True,
        False,
        [
            ('6254', None),
        ],
        'Péages / Parking',
        None,
    ),
    (
        '625500',
        True,
        False,
        [
            ('6255', None),
        ],
        'Remboursement kilométrique',
        None,
    ),
    (
        '625600',
        True,
        False,
        [
            ('6256', None),
        ],
        'Frais de mission',
        None,
    ),
    (
        '625700',
        True,
        False,
        [
            ('6257', None),
        ],
        'Frais de congrés',
        None,
    ),
    (
        '626100',
        True,
        False,
        [
            ('6261', None),
            ('6260', None),
            ('6263', None),
            ('6264', None),
            ('6266', None),
            ('6268', None),
        ],
        'Télécom',
        None,
    ),
    (
        '626200',
        True,
        False,
        [
            ('6262', None),
        ],
        'Frais postaux',
        None,
    ),
    (
        '627000',
        True,
        False,
        [
            ('627', None),
        ],
        'Frais bancaires',
        None,
    ),
    (
        '628000',
        True,
        False,
        [
            ('6280', None),
            ('6283', None),
            ('6284', None),
            ('6285', None),
            ('6288', None),
        ],
        'Autres frais de gestion',
        None,
    ),
    (
        '628100',
        True,
        False,
        [
            ('6281', None),
        ],
        'Abonnements et cotisations',
        None,
    ),
    (
        '628200',
        True,
        False,
        [
            ('6282', None),
        ],
        'Dons / pourboires',
        None,
    ),
    (
        '631100',
        True,
        False,
        [
            ('6311', None),
        ],
        'Taxe sur les salaires',
        None,
    ),
    (
        '631200',
        True,
        False,
        [
            ('6312', None),
        ],
        'Taxe d''apprentissage',
        None,
    ),
    (
        '631300',
        True,
        False,
        [
            ('6313', None),
        ],
        'Formation professionnelle continue',
        None,
    ),
    (
        '633300',
        True,
        False,
        [
            ('6333', None),
        ],
        'Formation',
        None,
    ),
    (
        '633500',
        True,
        False,
        [
            ('6335', None),
        ],
        'Versements libératoires ouvrant droit à l''exonération de la taxe d''apprentissage',
        None,
    ),
    (
        '633800',
        True,
        False,
        [
            ('6338', None),
        ],
        'Autres impôts et taxes',
        None,
    ),
    (
        '635110',
        True,
        False,
        [
            ('63511', None),
            ('63510', None),
        ],
        'Cotisations foncières des entreprises',
        None
    ),
    (
        '635120',
        True,
        False,
        [
            ('63512', None),
        ],
        'Taxes foncières',
        None,
    ),
    (
        '635130',
        True,
        False,
        [
            ('63513', None),
        ],
        'Autres impôts locaux',
        None,
    ),
    (
        '635140',
        True,
        False,
        [
            ('63514', None),
        ],
        'Taxes sur les véhicules',
        None,
    ),
    (
        '635200',
        True,
        False,
        [
            ('6352', None),
        ],
        'Taxes sur le chiffre d''affaires non déductibles',
        None,
    ),
    (
        '635400',
        True,
        False,
        [
            ('6354', None),
        ],
        'Droits d''enregistrement et de timbre',
        None,
    ),
    (
        '635800',
        True,
        False,
        [
            ('6358', None),
        ],
        'Autres taxes',
        None,
    ),
    (
        '637100',
        True,
        False,
        [
            ('6371', None),
        ],
        'Contribution sociale de solidarité des entreprises',
        None,
    ),
    (
        '637800',
        True,
        False,
        [
            ('6378', None),
        ],
        'CSG',
        None,
    ),
    (
        '641000',
        False,
        False,
        [
            ('6410', None),
            ('6411', None),
            ('6412', None),
            ('6413', None),
            ('6415', None),
            ('6416', None),
            ('6417', None),
        ],
        'Salaires bruts',
        None,
    ),
    (
        '641200',
        False,
        False,
        [
            ('6412', None),
        ],
        'Congés payés',
        None,
    ),
    (
        '641300',
        False,
        False,
        [
            ('6413', None),
        ],
        'Primes et gratifications',
        None,
    ),
    (
        '641400',
        True,
        False,
        [
            ('6414', None),
        ],
        'Stagiaires',
        None,
    ),
    (
        '644000',
        True,
        True,
        [
            ('644', 3),
        ],
        'Rémunération du dirigeant', 'numéro associé',
    ),
    (
        '645000',
        True,
        True,
        [
            ('6450', 3),
            ('6451', 3),
            ('6452', 3),
            ('6453', 3),
            ('6454', 3),
            ('6455', 3),
            ('6456', 3),
            ('6457', 3),
        ],
        'Charges sociales salariales versées',
        'numéro organisme social',
    ),
    (
        '645800',
        True,
        True,
        [
            ('6458', 3),
            ('6459', 3),
        ],
        'Cotisations aux autres organismes',
        'numéro organisme social',
    ),
    (
        '646000',
        True,
        True,
        [
            ('6460', 4),
            ('6461', 4),
            ('6462', 4),
            ('6463', 4),
            ('6464', 4),
            ('6465', 4),
            ('6469', 4),
        ],
        'Cotisations sociales obligatoires du dirigeant',
        'numéro organisme social',
    ),
    (
        '646600',
        True,
        True,
        [
            ('6466', 4),
            ('6467', 4),
            ('6468', 4),
        ],
        'Cotisations sociales complémentaires du dirigeant',
        'numéro organisme social',
    ),
    (
        '647000',
        True,
        True,
        [
            ('6470', 3),
        ],
        'Autres charges sociales', 'numéro organisme social',
    ),
    (
        '647100',
        True,
        False,
        [
            ('6471', None),
        ],
        'PEE',
        None,
    ),
    (
        '647200',
        True,
        False,
        [
            ('6472', None),
        ],
        'PERCO',
        None,
    ),
    (
        '647500',
        True,
        False,
        [
            ('6475', None),
        ],
        'Médecine du travail',
        None,
    ),
    (
        '647800',
        True,
        False,
        [
            ('6478', None),
        ],
        'Tickets restaurants',
        None,
    ),
    (
        '648000',
        True,
        True,
        [
            ('6480', 3),
        ],
        'Autres charges de personnel', 'numéro roganisme social',
    ),
    (
        '648100',
        True,
        False,
        [
            ('6481', None),
        ],
        'CESU',
        None,
    ),
    (
        '651000',
        True,
        False,
        [
            ('651', None),
        ],
        'Redevance de brevet',
        None,
    ),
    (
        '654000',
        True,
        False,
        [
            ('654', None),
        ],
        'Pertes sur créances irrécouvrables',
        None,
    ),
    (
        '658000',
        True,
        False,
        [
            ('658', None),
        ],
        'Charges diverses de gestion courante',
        None,
    ),
    (
        '661000',
        True,
        False,
        [
            ('6610', None),
        ],
        'Charges d''intérêts',
        None,
    ),
    (
        '661100',
        True,
        False,
        [
            ('66110', None),
            ('66111', None),
            ('66112', None),
            ('66113', None),
            ('66114', None),
            ('66115', None),
            ('66118', None),
        ],
        'Intérêts des emprunts et dettes',
        None,
    ),
    (
        '661160',
        True,
        False,
        [
            ('66116', None),
        ],
        'Intérêts des emprunts et dettes assimilées',
        None,
    ),
    (
        '661200',
        True,
        False,
        [
            ('6612', None),
        ],
        'Intérêts des emprunts et dettes',
        None,
    ),
    (
        '661500',
        True,
        False,
        [
            ('6615', None),
        ],
        'Intérêts des comptes courants et des dépôts créditeurs',
        None,
    ),
    (
        '661600',
        True,
        False,
        [
            ('6616', None),
        ],
        'Agios',
        None,
    ),
    (
        '661800',
        True,
        False,
        [
            ('6618', None),
        ],
        'Intérêts des emprunts et dettes',
        None,
    ),
    (
        '665000',
        True,
        False,
        [
            ('665', None),
        ],
        'Escomptes accordés',
        None,
    ),
    (
        '666000',
        True,
        False,
        [
            ('666', None),
        ],
        'Pertes de change',
        None,
    ),
    (
        '667000',
        True,
        False,
        [
            ('667', None),
        ],
        'Charges nettes sur cessions de valeurs mobilières de placement',
        None,
    ),
    (
        '668000',
        True,
        False,
        [
            ('668', None),
        ],
        'Autres charges financières',
        None,
    ),
    (
        '671000',
        True,
        False,
        [
            ('6710', None),
        ],
        'Charges exceptionnelles sur opérations de gestion',
        None,
    ),
    (
        '671200',
        True,
        False,
        [
            ('6712', None),
        ],
        'Amendes',
        None,
    ),
    (
        '671800',
        True,
        False,
        [
            ('6718', None),
        ],
        'Autres charges exceptionnelles sur opérations de gestion',
        None,
    ),
    (
        '672000',
        False,
        False,
        [
            ('672', None),
        ],
        'Charges sur exercices antérieurs',
        None,
    ),
    (
        '675000',
        False,
        False,
        [
            ('675', None),
        ],
        'Valeurs comptables des éléments d''actif cédés',
        None,
    ),
    (
        '681100',
        False,
        False,
        [
            ('6811', None),
        ],
        'Dotations aux amortissements sur immobilisations incorporelles et corporelles',
        None,
    ),
    (
        '681700',
        False,
        False,
        [
            ('6817', None),
        ],
        'Dotations aux provisions pour dépréciation des actifs circulants',
        None,
    ),
    (
        '681730',
        False,
        False,
        [
            ('68173', None),
        ],
        'Stocks et en-cours',
        None,
    ),
    (
        '681740',
        False,
        False,
        [
            ('68174', None),
        ],
        'Créances',
        None,
    ),
    (
        '686000',
        False,
        False,
        [
            ('686', None),
        ],
        'Dotations aux amortissements et aux provisions - Charges financières',
        None,
    ),
    (
        '687000',
        False,
        False,
        [
            ('687', None),
        ],
        'Dotations aux amortissements et aux provisions - Charges exceptionnelles',
        None,
    ),
    (
        '691000',
        False,
        False,
        [
            ('691', None),
        ],
        'Participation des salariés aux résultats',
        None,
    ),
    (
        '695000',
        False,
        False,
        [
            ('695', None),
        ],
        'Impôts sur les bénéfices',
        None,
    ),
    (
        '697000',
        False,
        False,
        [
            ('697', None),
        ],
        'Imposition forfaitaire annuelle des sociétés',
        None,
    ),
    (
        '699000',
        False,
        False,
        [
            ('699', None),
        ],
        'Produits - Reports en arrière des déficits',
        None,
    ),
    (
        '701000',
        True,
        False,
        [
            ('701', None),
        ],
        'Ventes de biens',
        None,
    ),
    (
        '702000',
        True,
        False,
        [
            ('702', None),
        ],
        'Ventes de produits intermédiaires',
        None,
    ),
    (
        '703000',
        True,
        False,
        [
            ('703', None),
        ],
        'Ventes de produits résiduels',
        None,
    ),
    (
        '704000',
        True,
        False,
        [
            ('704', None),
        ],
        'Travaux',
        None,
    ),
    (
        '705000',
        True,
        False,
        [
            ('705', None),
        ],
        'Etudes',
        None,
    ),
    (
        '706000',
        True,
        False,
        [
            ('706', None),
        ],
        'Recettes prestations de services',
        None,
    ),
    (
        '707000',
        True,
        False,
        [
            ('707', None),
        ],
        'Ventes de marchandises',
        None,
    ),
    (
        '708000',
        True,
        False,
        [
            ('708', None),
        ],
        'Revenus des activités annexes',
        None,
    ),
    (
        '709000',
        True,
        False,
        [
            ('709', None),
        ],
        'Rabais, remises et ristournes accordés par l''entreprise',
        None,
    ),
    (
        '713000',
        False,
        False,
        [
            ('7130', None),
        ],
        'Variation des stocks (en-cours de production, produits)',
        None,
    ),
    (
        '713300',
        False,
        False,
        [
            ('71330', None),
        ],
        'Variation des en-cours de production de biens',
        None,
    ),
    (
        '713310',
        False,
        False,
        [
            ('71331', None),
        ],
        'Produits en cours',
        None,
    ),
    (
        '713350',
        False,
        False,
        [
            ('71335', None),
        ],
        'Travaux en cours',
        None,
    ),
    (
        '713400',
        False,
        False,
        [
            ('71340', None),
        ],
        'Variation des en-cours de production de services',
        None,
    ),
    (
        '713410',
        False,
        False,
        [
            ('71341', None),
        ],
        'Etudes en cours',
        None,
    ),
    (
        '713450',
        False,
        False,
        [
            ('71345', None),
        ],
        'Prestations de services en cours',
        None,
    ),
    (
        '713500',
        False,
        False,
        [
            ('71350', None),
        ],
        'Variation des stocks de produits',
        None,
    ),
    (
        '713510',
        False,
        False,
        [
            ('71351', None),
        ],
        'Produits intermédiaires',
        None,
    ),
    (
        '713550',
        False,
        False,
        [
            ('71355', None),
        ],
        'Produits finis',
        None,
    ),
    (
        '713580',
        False,
        False,
        [
            ('71358', None),
        ],
        'Produits résiduels',
        None,
    ),
    (
        '721000',
        False,
        False,
        [
            ('721', None),
        ],
        'Production immobilisations incorporelles',
        None,
    ),
    (
        '722000',
        False,
        False,
        [
            ('722', None),
        ],
        'Production Immobilisations corporelles',
        None,
    ),
    (
        '740000',
        True,
        False,
        [
            ('74', None),
        ],
        'Subventions',
        None,
    ),
    (
        '751000',
        True,
        False,
        [
            ('751', None),
        ],
        'Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires',
        None,
    ),
    (
        '758000',
        True,
        False,
        [
            ('758', None),
        ],
        'Produits divers de gestion courante',
        None,
    ),
    (
        '761000',
        True,
        False,
        [
            ('761', None),
        ],
        'Produits de participations',
        None,
    ),
    (
        '762000',
        True,
        False,
        [
            ('762', None),
        ],
        'Produits des autres immobilisations financières',
        None,
    ),
    (
        '763000',
        True,
        False,
        [
            ('763', None),
        ],
        'Revenus des autres créances',
        None,
    ),
    (
        '764000',
        True,
        False,
        [
            ('764', None),
        ],
        'Revenus des valeurs mobilières de placement',
        None,
    ),
    (
        '765000',
        True,
        False,
        [
            ('765', None),
        ],
        'Escomptes obtenus',
        None,
    ),
    (
        '766000',
        True,
        False,
        [
            ('766', None),
        ],
        'Gains de change',
        None,
    ),
    (
        '767000',
        True,
        False,
        [
            ('767', None),
        ],
        'Produits nets sur cessions de valeurs mobilières de placement',
        None,
    ),
    (
        '768000',
        True,
        False,
        [
            ('768', None),
        ],
        'Produits financiers',
        None,
    ),
    (
        '771000',
        True,
        False,
        [
            ('771', None),
        ],
        'Produits exceptionnels sur opérations de gestion',
        None,
    ),
    (
        '772000',
        True,
        False,
        [
            ('772', None),
        ],
        'Produits sur exercices antérieurs',
        None,
    ),
    (
        '775000',
        True,
        False,
        [
            ('775', None),
        ],
        'Vente d''un investissement',
        None,
    ),
    (
        '777000',
        False,
        False,
        [
            ('777', None),
        ],
        'Quote-part des subventions d''investissement virée au résultat de l''exercice',
        None,
    ),
    (
        '786000',
        False,
        False,
        [
            ('786', None),
        ],
        'Reprises sur provisions pour risques (à inscrire dans les produits financiers)',
        None,
    ),
    (
        '787000',
        False,
        False,
        [
            ('787', None),
        ],
        'Reprises sur provisions (à inscrire dans les produits exceptionnels)',
        None,
    ),
    (
        '791000',
        True,
        False,
        [
            ('791', None),
        ],
        'Transferts de charges d''exploitations',
        None,
    ),
    (
        '796000',
        True,
        False,
        [
            ('796', None),
        ],
        'Transferts de charges financières',
        None,
    ),
    (
        '797000',
        True,
        False,
        [
            ('797', None),
        ],
        'Transferts de charges exceptionnelles',
        None,
    ),
]
